version: '3.8'
services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
